#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 006: Bulk Selection and Batch Actions

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Spec 006: Bulk Selection and Batch Actions"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# PREREQUISITES CHECK
# ============================================

echo ""
echo "Checking prerequisites..."

# Check Node.js
if ! command -v node &> /dev/null; then
    echo -e "${RED}Node.js not found. Please install Node.js.${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Node.js $(node --version)${NC}"

# Check npm
if ! command -v npm &> /dev/null; then
    echo -e "${RED}npm not found. Please install npm.${NC}"
    exit 1
fi
echo -e "${GREEN}✓ npm $(npm --version)${NC}"

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing dependencies..."
if [ ! -d "node_modules" ]; then
    npm install
else
    echo -e "${YELLOW}node_modules exists, skipping install. Run 'npm install' manually if needed.${NC}"
fi

# ============================================
# ENVIRONMENT VARIABLES CHECK
# ============================================

echo ""
echo "Checking environment variables..."

if [ ! -f ".env" ]; then
    echo -e "${YELLOW}Warning: .env file not found${NC}"
    echo "Creating from .env.example..."
    if [ -f ".env.example" ]; then
        cp .env.example .env
        echo -e "${YELLOW}Please edit .env with your qBittorrent connection details${NC}"
    else
        echo -e "${RED}No .env.example found${NC}"
    fi
else
    echo -e "${GREEN}✓ .env file exists${NC}"
fi

# ============================================
# START SERVICES
# ============================================

echo ""
echo "========================================"
echo "Starting React Frontend (main service)"
echo "========================================"

# Check if port 3000 is already in use
if lsof -Pi :3000 -sTCP:LISTEN -t >/dev/null 2>&1; then
    echo -e "${YELLOW}Port 3000 is already in use${NC}"
    echo "Either:"
    echo "  1. Kill the existing process using port 3000"
    echo "  2. The dev server is already running"
else
    # Start dev server in background
    npm run dev &
    DEV_PID=$!

    # Wait for service to be ready
    wait_for_service 3000 "React Frontend"
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend: http://localhost:3000"
echo ""
echo "To stop services:"
echo "  - Press Ctrl+C or run: kill $DEV_PID"
echo ""
echo "Next Steps:"
echo "  1. Open http://localhost:3000 in your browser"
echo "  2. Login with qBittorrent credentials"
echo "  3. Implementation will add bulk selection features"
echo ""
echo "========================================"
echo "Implementation Plan Summary"
echo "========================================"
echo ""
echo "Phase 1: UI Foundation (3 subtasks)"
echo "  - Create Checkbox component"
echo "  - Add checkboxes to TorrentTable"
echo "  - Add checkboxes to TorrentCard"
echo ""
echo "Phase 2: Selection State (3 subtasks)"
echo "  - Implement selection state management"
echo "  - Wire state to components"
echo "  - Add 'Select All' functionality"
echo ""
echo "Phase 3: Batch Actions UI (2 subtasks)"
echo "  - Create BatchActionsToolbar component"
echo "  - Integrate toolbar into main page"
echo ""
echo "Phase 4: Batch Operations (4 subtasks)"
echo "  - Add category assignment API"
echo "  - Create batch pause/resume mutations"
echo "  - Create batch delete with confirmation"
echo "  - Add batch category assignment"
echo ""
echo "Phase 5: Integration (3 subtasks)"
echo "  - Add loading states"
echo "  - Handle edge cases"
echo "  - End-to-end verification"
echo ""
echo "Total: 5 phases, 14 subtasks"
echo ""
