#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for: Add Torrents via Magnet Links and Torrent Files

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# CHECK PREREQUISITES
# ============================================

echo ""
echo "Checking prerequisites..."

# Load nvm and use Node version from .nvmrc
if [ -s "$HOME/.nvm/nvm.sh" ]; then
    echo "Loading nvm..."
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

    if [ -f ".nvmrc" ]; then
        echo "Using Node.js version from .nvmrc..."
        nvm use
    fi
fi

# Check Node.js
if ! command -v node &> /dev/null; then
    echo -e "${RED}Node.js is not installed${NC}"
    exit 1
fi
echo -e "${GREEN}Node.js: $(node --version)${NC}"

# Check npm
if ! command -v npm &> /dev/null; then
    echo -e "${RED}npm is not installed${NC}"
    exit 1
fi
echo -e "${GREEN}npm: $(npm --version)${NC}"

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing dependencies..."
npm install

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting React development server..."
npm run dev &
DEV_PID=$!

wait_for_service 3000 "React Dev Server"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend: http://localhost:3000"
echo ""
echo "Make sure qBittorrent WebUI is running at the configured URL"
echo "(check .env or localStorage for VITE_QBIT_BASE_URL)"
echo ""
echo "Press Ctrl+C to stop the development server"
echo ""

# Wait for the dev server
wait $DEV_PID
